# Generated by Django 2.1 on 2019-05-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatalHoroscope',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('time_of_birth_hh', models.CharField(max_length=2, null=True, verbose_name='Time of Birth Hour')),
                ('time_of_birth_mm', models.CharField(max_length=2, null=True, verbose_name='Time of Birth Minute')),
                ('time_of_birth_ss', models.CharField(max_length=2, null=True, verbose_name='Time of Birth Second')),
                ('place_of_birth', models.CharField(max_length=80, verbose_name='Place of Birth')),
                ('current_location', models.CharField(max_length=80, verbose_name='Current Location')),
                ('email_addr', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_email', models.EmailField(max_length=254)),
                ('amount', models.FloatField()),
                ('paid_status', models.BooleanField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField(null=True)),
                ('charge_id', models.CharField(max_length=32, null=True, verbose_name='Charge ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samayanandaa_web.NatalHoroscope')),
            ],
        ),
    ]
