# Generated by Django 2.1.1 on 2020-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samayanandaa_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natalhoroscope',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
