# Generated by Django 2.1.1 on 2020-12-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samayanandaa_web', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client_id',
        ),
    ]
