# Generated by Django 2.1.1 on 2021-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samayanandaa_web', '0004_remove_feedback_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_message_content',
            field=models.CharField(max_length=2000),
        ),
    ]
